# Nixpacks Configuration for ViuWi Next.js Application
# Simplified configuration that leverages nixpacks' automatic pnpm detection
# Optimized for Next.js 15.4.6 with React 19 and production deployment

# =============================================================================
# ENVIRONMENT VARIABLES
# =============================================================================
[variables]
# Use Node.js 20 for better performance and caching
NIXPACKS_NODE_VERSION = "20"

# Production environment settings
NODE_ENV = "production"
CI = "true"

# Next.js optimizations
NEXT_TELEMETRY_DISABLED = "1"  # Disable telemetry for faster builds

# =============================================================================
# BUILD PHASES
# =============================================================================

# -----------------------------------------------------------------------------
# SETUP PHASE: Install system packages and tools
# -----------------------------------------------------------------------------
[phases.setup]
# Essential system packages for Node.js and Next.js builds
# Note: pnpm is automatically detected and installed by nixpacks from pnpm-lock.yaml
nixPkgs = [
  "nodejs_20",     # Node.js 20 for better performance
  "python3",       # Required for some native dependencies
  "gcc",           # C compiler for native modules
  "pkg-config",    # Package configuration tool
  "git"            # Git for potential dependency resolution
  "pnpm"
]
[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build] 
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
# =============================================================================
# OPTIMIZATION NOTES
# =============================================================================
# This simplified configuration:
# 1. Leverages nixpacks' automatic pnpm detection from pnpm-lock.yaml
# 2. Uses Corepack support via packageManager field in package.json
# 3. Relies on nixpacks' built-in caching for optimal performance
# 4. Removes manual phase definitions to use nixpacks defaults
# 5. Maintains essential system dependencies for native modules
